config/routes.rb
Bouncer::Application.routes.draw do
  root 'pages#welcome'
  get 'attendees' => 'event_attendees#index'

  devise_for :users,
    :path_names => { :sign_in => 'login', :sign_out => 'logout' },
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" },
    :skip => [:registration]

  ActiveAdmin.routes(self)

  

end

app/models/event_attendee.rb
# == Schema Information
#
# Table name: event_attendees
#
#  id                   :integer          not null, primary key
#  ticket_created_date  :datetime
#  manhattanjs_event_id :integer
#  ticket               :string(255)
#  ticket_full_name     :string(255)
#  ticket_first_name    :string(255)
#  ticket_last_name     :string(255)
#  ticket_email         :string(255)
#  event                :string(255)
#  void_status          :string(255)
#  price                :integer
#  ticket_reference     :string(255)
#  order_reference      :string(255)
#  order_email          :string(255)
#

class EventAttendee < ActiveRecord::Base
  belongs_to :manhattanjs_event
end

app/models/manhattanjs_event.rb
# == Schema Information
#
# Table name: manhattanjs_events
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  event_date :datetime
#  created_at :datetime
#  updated_at :datetime
#

class ManhattanjsEvent < ActiveRecord::Base
	has_many :event_attendees
	has_many :attendees, through: :event_attendees
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#  avatar                 :string(255)
#

class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :trackable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  # :email, :password, :password_confirmation, :remember_me, :avatar, :name

  def self.find_or_create_google(auth_hash)
    user = where(email: auth_hash[:info][:email]).first_or_create! do |u|
      u.password = Devise.friendly_token[0,20]
    end
    user.name = auth_hash[:info][:name]
    user.avatar = auth_hash[:info][:image]
    user.save if user.changed?
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  def index
  	@events = ManhattanjsEvent.upcoming
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_filter :check_domain

  def google_oauth2
    @user = User.find_or_create_google(request.env["omniauth.auth"])
    unless @user.valid?
      set_flash_message(:notice, :success, :kind => "Google")
      return redirect_to :root
    end

    sign_in_and_redirect @user, :event => :authentication
  end

  private

  def check_domain
    valid_domains = ['manhattanjs.com']
    users_domain = request.env["omniauth.auth"][:extra][:raw_info][:hd]
    #email = request.env["omniauth.auth"][:info][:email]
    #cool_users = ['qreid51@gmail.com', 'rushaine.mcbean@gmail.com']
    unless valid_domains.include?(users_domain) 
      # flash wrong domain
      return redirect_to :root
    end
  rescue
    # flash something went wrong?
    return redirect_to :root
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/event_attendees/index.html.erb
<h1> <%= @event.name %> </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/_admin_actions.html.erb
<% if signed_in? %>
	<%= link_to 'Create a New Event', admin_manhattanjs_events_path %>
	<%= link_to 'Attendees List', event_attendee_path %> 
<% end %>

app/views/pages/welcome.html.erb
<%= include_ember_script_tags :bodyguard %>
<%= include_ember_stylesheet_tags :bodyguard %>

app/views/shared/_google_auth.html.erb
<% if signed_in? %>
Would you like to <%= link_to 'sign out', destroy_user_session_path, method: :delete %>?
<% else %>
hi! <%= link_to "Sign in with Google Apps", user_omniauth_authorize_path(:google_oauth2) %>
<% end %>